services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: plm_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U admin -d plm_db" ]
          interval: 5s
          timeout: 5s
          retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./csv:/csv

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/plm_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL-AUTO: validate
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: