CREATE TABLE IF NOT EXISTS plm (
    s_PK INTEGER PRIMARY KEY,
    s_ObjectID INTEGER,
    s_Guid UUID,
    s_Version INTEGER,
    s_ActualVersion INTEGER,
    s_ClientViewID INTEGER,
    s_Deleted INTEGER,
    s_State INTEGER,
    s_AuthorID INTEGER,
    s_CreationDate TIMESTAMP,
    s_EditorID INTEGER,
    s_EditDate TIMESTAMP,
    s_ClassID INTEGER,
    s_AccessObjectID INTEGER,
    s_SourceVersion INTEGER,
    s_StageID INTEGER,
    s_LinkedObjectID INTEGER,
    s_LinkedObjectClassID INTEGER,
    s_AccessLevel INTEGER,
    s_OwnerID INTEGER,
    s_LogicalObjectGuid UUID,
    s_RevisionName VARCHAR(255),
    s_ActualRevision INTEGER,
    oboznachenie_421975 VARCHAR(255),
    Name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS plmhierarchy (
    s_PK INTEGER PRIMARY KEY,
    s_ObjectID INTEGER,
    s_Guid UUID,
    s_Version INTEGER,
    s_ActualVersion INTEGER,
    s_ClientViewID INTEGER,
    s_Deleted INTEGER,
    s_State INTEGER,
    s_ParentID INTEGER,
    s_FirstUse INTEGER,
    s_HierarchyLinkID INTEGER
);

CREATE TABLE IF NOT EXISTS classes (
    PK INTEGER PRIMARY KEY,
    Guid UUID,
    GroupID INTEGER,
    BaseClassID INTEGER,
    Name VARCHAR(255),
    Comment VARCHAR(255),
    Icon BYTEA,
    Sealed BOOLEAN,
    "abstract" BOOLEAN,
    UseBaseClassIcon BOOLEAN,
    Root BOOLEAN,
    SystemType INTEGER,
    PropertiesDisplayType INTEGER,
    CreateFromPrototype BOOLEAN,
    SupportsSaveAndCreate BOOLEAN,
    UniqueIndexID INTEGER,
    SchemeID INTEGER,
    DefaultStageID INTEGER,
    LinkedClassID INTEGER,
    LinkedInheritClasses VARCHAR(255),
    Attributes VARCHAR(255),
    CanChange BOOLEAN,
    InheritMasterClasses BOOLEAN,
    Hidden BOOLEAN,
    ObjectFormat VARCHAR(255),
    SupportMultiAttachment BOOLEAN
);